language: rust
sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran
      - libblas3gf
      - liblapack3gf

matrix:
  allow_failures:
    - rust: nightly

env:
  matrix:
    - CARGO_FEATURE_SYSTEM_NETLIB=1 CARGO_FEATURE_EXCLUDE_LAPACKE=1 CARGO_FEATURE_EXCLUDE_CBLAS=1
